backend/backend/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    # path('mr/', include('merchant.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/myapp/urls.py
from django.urls import path
from .views import *
from . import views
app_name = 'myapp'
urlpatterns = [
#Shop View
    path('shopview1/', views.shopview1, name='shopview1'),
    path('shopview2/', views.shopview2, name='shopview2'),
    path('login/',views.loginpage, name='login'),
    # path('logout/', views.logoutuser, name='logoutuser'),

    path('', views.home, name='home'),
    path('create_item/', views.create_item, name='create_item'),
    path('category_list/', views.category_list, name='category_list'),
    path('item_details/1/', views.item_details, name='item_details'),


]

backend/myapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Warehouse(models.Model):
    warehouse_name = models.CharField(max_length=255)
    def __str__(self):
        return self.warehouse_name

class StaffPermission(models.Model):
    usr = models.ForeignKey(User, on_delete=models.CASCADE)
    manager = models.BooleanField(default=False)
    admin = models.BooleanField(default=False)
    supervisor = models.BooleanField(default=False)

class Category(models.Model):
    category_name = models.CharField(max_length=255)
    created = models.DateField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

class Items(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    item_name = models.CharField(max_length=255)
    photo = models.ImageField(upload_to='item/')
    price1 = models.PositiveIntegerField(default=0)
    price2 = models.PositiveIntegerField(default=0)
    price3 = models.PositiveIntegerField(default=0)
    price4 = models.PositiveIntegerField(default=0)
    package_unit = models.CharField(max_length=100,blank=True, null=True)
    description = models.TextField(blank=True, null=True)

    created = models.DateField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


class ItmColor(models.Model):
    items = models.ForeignKey(Items, on_delete=models.CASCADE)
    color = models.CharField(max_length=255,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.color

class ItmSize(models.Model):
    items = models.ForeignKey(Items, on_delete=models.CASCADE)
    size = models.CharField(max_length=255,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.size


class ItemWarehouse(models.Model):
    items = models.ForeignKey(Items, on_delete=models.CASCADE)
    warehouse = models.ForeignKey(Warehouse, on_delete=models.CASCADE)
    color = models.ForeignKey(ItmColor, on_delete=models.CASCADE, blank=True, null=True)
    size = models.ForeignKey(ItmSize, on_delete=models.CASCADE, blank=True, null=True)
    stock_balance = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

backend/myapp/forms.py
from django import forms
from .models import *


class ULoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())

class ItemsForm(forms.ModelForm):
    class Meta:
        model = Items
        fields = ['item_name','category','price1','price2','price3','price4','package_unit','description','photo']
        widgets = {
            'item_name': forms.TextInput(attrs={'class': 'form-control col-md-6'}),
            'category': forms.Select(attrs={'class': 'form-control col-md-6'}),
            'price1': forms.NumberInput(attrs={'class': 'form-control w-50'}),
            'price2': forms.NumberInput(attrs={'class': 'form-control w-50'}),
            'price3': forms.NumberInput(attrs={'class': 'form-control w-50'}),
            'price4': forms.NumberInput(attrs={'class': 'form-control w-50'}),
            'package_unit': forms.TextInput(attrs={'class': 'form-control col-md-6'}),
            'description': forms.Textarea(attrs={'class': 'form-control col-md-6'}),
            'photo':forms.FileInput(attrs={'class':'form-control'}),
        }

backend/myapp/views.py
import datetime

from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import AnonymousUser
from django.db.models import Sum,Count,F
from django.http import HttpResponse
from django.views.generic import TemplateView, View, CreateView, DetailView,FormView,ListView
# import generic UpdateView
from django.views.generic.edit import DeleteView

from django.urls import reverse_lazy
from django.http import JsonResponse
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import *
from .models import *

def loginpage(request):
    if request.user.is_authenticated:
        return redirect('myapp:home')
    else:
        if request.method == "POST":
            username=request.POST.get('username')
            password=request.POST.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('myapp:home')
            else:
                messages.info(request, 'username or password invalid')
            # return render(request, 'login.html', context)
        context ={}
        return render(request, 'shop/login.html', context)

@login_required(login_url='myapp:login')
def home(request):
    try:
        p = StaffPermission.objects.get(usr = request.user)
        # print(p.hr)
        if p.manager is True:
            return render(request, 'shop/dashboard.html')
        
        elif p.admin is True:
            print('Admin')
        elif p.supervisor is True:
            print('Supervisor')
        else:    
            return render(request, 'shop/dashboard.html')
    except StaffPermission.DoesNotExist:
        # return HttpResponse('hellllo')
        return redirect('myapp:login')


def create_item(request):
    fm = ItemsForm()
    context = {'fm':fm}
    return render(request, 'shop/create_item.html',context)

def category_list(request):
    context = {}
    return render(request, 'shop/category_list.html',context)

def item_details(request):
    context = {}
    return render(request, 'shop/item_details.html',context)


# SHOP
def shopview1(request):
    context = {}
    return render(request, 'shopview1.html',context)
    
def shopview2(request):
    context = {}
    return render(request, 'shopview2.html',context)

backend/templates/base.html
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="en">

<!-- belle/shop-grid-7.html   11 Nov 2019 12:41:01 GMT -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="x-ua-compatible" content="ie=edge">
<title>Myanamr K Power Company</title>
<meta name="description" content="description">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Favicon -->
<link rel="shortcut icon" href="{% static 'belle/assets/images/favicon.png' %}" />
<!-- Plugins CSS -->
<link rel="stylesheet" href="{% static 'belle/assets/css/plugins.css' %}">
<!-- Bootstap CSS -->
<link rel="stylesheet" href="{% static 'belle/assets/css/bootstrap.min.css' %}">
<!-- Main Style CSS -->
<link rel="stylesheet" href="{% static 'belle/assets/css/style.css' %}">
<link rel="stylesheet" href="{% static 'belle/assets/css/responsive.css' %}">
</head>
<body class="template-collection belle">
<div class="pageWrapper">
	<!--Search Form Drawer-->
	<div class="search">
        <div class="search__form">
            <form class="search-bar__form" action="#">
                <button class="go-btn search__button" type="submit"><i class="icon anm anm-search-l"></i></button>
                <input class="search__input" type="search" name="q" value="" placeholder="Search entire store..." aria-label="Search" autocomplete="off">
            </form>
            <button type="button" class="search-trigger close-btn"><i class="icon anm anm-times-l"></i></button>
        </div>
    </div>
    <!--End Search Form Drawer-->

    <!--Header-->
    <div class="header-wrap animated d-flex">
    	<div class="container-fluid">        
            <div class="row align-items-center">
            	<!--Desktop Logo-->
                <div class="logo col-md-2 col-lg-2 d-none d-lg-block">
                    <a href="#">
                    	<img src="{% static 'belle/assets/images/mobile.png' %}" alt=" Template" title="Template" />
                    </a>
                </div>
                <!--End Desktop Logo-->
                <div class="col-2 col-sm-3 col-md-3 col-lg-8">
                	<div class="d-block d-lg-none">
                        <button type="button" class="btn--link site-header__menu js-mobile-nav-toggle mobile-nav--open">
                        	<i class="icon anm anm-times-l"></i>
                            <i class="anm anm-bars-r"></i>
                        </button>
                    </div>
                	<!--Desktop Menu-->
                	<nav class="grid__item" id="AccessibleNav"><!-- for mobile -->
                        <ul id="siteNav" class="site-nav medium center hidearrow">
                            
                        <li class="lvl1"><a href="#"><b>Home</b> <i class="anm anm-angle-down-l"></i></a></li>
                        <li class="lvl1"><a href="#"><b>Shop</b> <i class="anm anm-angle-down-l"></i></a></li>
                        <li class="lvl1"><a href="#"><b>Contact</b> <i class="anm anm-angle-down-l"></i></a></li>
                        <li class="lvl1"><a href="#"><b>Cart</b> <i class="anm anm-angle-down-l"></i></a></li>
                      </ul>
                    </nav>
                    <!--End Desktop Menu-->
                </div>
                <div class="col-6 col-sm-6 col-md-6 col-lg-2 d-block d-lg-none mobile-logo">
                	<div class="logo">
                        <a href="">
                            <img src="{% static 'belle/assets/images/mobile.png' %}" alt="Template" title="Template" />
                        </a>
                    </div>
                </div>
                <div class="col-4 col-sm-3 col-md-3 col-lg-2">
                	<div class="site-cart">
                    	<a href="#;" class="site-header__cart" title="Cart">
                        	<i class="icon anm anm-bag-l"></i>
                            <span id="CartCount" class="site-header__cart-count" data-cart-render="item_count">2</span>
                        </a>
                        <!--Minicart Popup-->
                        <div id="header-cart" class="block block-cart">
                            <ul class="mini-products-list">
                                <li class="item">
                                    <a class="product-image" href="#">
                                        <img src="assets/images/product-images/cape-dress-1.jpg" alt="3/4 Sleeve Kimono Dress" title="" />
                                    </a>
                                    <div class="product-details">
                                        <a href="#" class="remove"><i class="anm anm-times-l" aria-hidden="true"></i></a>
                                        <a href="#" class="edit-i remove"><i class="anm anm-edit" aria-hidden="true"></i></a>
                                        <a class="pName" href="cart.html">Sleeve Kimono Dress</a>
                                        <div class="variant-cart">Black / XL</div>
                                        <div class="wrapQtyBtn">
                                            <div class="qtyField">
                                                <span class="label">Qty:</span>
                                                <a class="qtyBtn minus" href="javascript:void(0);"><i class="fa anm anm-minus-r" aria-hidden="true"></i></a>
                                                <input type="text" id="Quantity" name="quantity" value="1" class="product-form__input qty">
                                                <a class="qtyBtn plus" href="javascript:void(0);"><i class="fa anm anm-plus-r" aria-hidden="true"></i></a>
                                            </div>
                                        </div>
                                        <div class="priceRow">
                                            <div class="product-price">
                                                <span class="money">$59.00</span>
                                            </div>
                                         </div>
                                    </div>
                                </li>
                                <li class="item">
                                    <a class="product-image" href="#">
                                        <img src="assets/images/product-images/cape-dress-2.jpg" alt="Elastic Waist Dress - Black / Small" title="" />
                                    </a>
                                    <div class="product-details">
                                        <a href="#" class="remove"><i class="anm anm-times-l" aria-hidden="true"></i></a>
                                        <a href="#" class="edit-i remove"><i class="anm anm-edit" aria-hidden="true"></i></a>
                                        <a class="pName" href="cart.html">Elastic Waist Dress</a>
                                        <div class="variant-cart">Gray / XXL</div>
                                        <div class="wrapQtyBtn">
                                            <div class="qtyField">
                                                <span class="label">Qty:</span>
                                                <a class="qtyBtn minus" href="javascript:void(0);"><i class="fa anm anm-minus-r" aria-hidden="true"></i></a>
                                                <input type="text" id="Quantity" name="quantity" value="1" class="product-form__input qty">
                                                <a class="qtyBtn plus" href="javascript:void(0);"><i class="fa anm anm-plus-r" aria-hidden="true"></i></a>
                                            </div>
                                        </div>
                                        <div class="priceRow">
                                            <div class="product-price">
                                                <span class="money">$99.00</span>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                            <div class="total">
                                <div class="total-in">
                                    <span class="label">Cart Subtotal:</span><span class="product-price"><span class="money">$748.00</span></span>
                                </div>
                                 <div class="buttonSet text-center">
                                    <a href="cart.html" class="btn btn-secondary btn--small">View Cart</a>
                                    <a href="checkout.html" class="btn btn-secondary btn--small">Checkout</a>
                                </div>
                            </div>
                        </div>
                        <!--End Minicart Popup-->
                    </div>
                    <div class="site-header__search">
                    	<button type="button" class="search-trigger"><i class="icon anm anm-search-l"></i></button>
                    </div>
                </div>
        	</div>
        </div>
    </div>
    <!--End Header-->
    <!--Mobile Menu-->
    <div class="mobile-nav-wrapper" role="navigation">
		<div class="closemobileMenu"><i class="icon anm anm-times-l pull-right"></i> Close Menu</div>
        <ul id="MobileNav" class="mobile-nav">
        	
        	<li class="lvl1"><a href="#"><b>Home</b></a></li>
        	<li class="lvl1"><a href="#"><b>Shop</b></a></li>
        	<li class="lvl1"><a href="#"><b>Cart</b></a></li>
        	<li class="lvl1"><a href="#"><b>Contact</b></a></li>
      </ul>
	</div>
	<!--End Mobile Menu-->
    
    <!--Body Content-->
    <div id="page-content">
    	<!--Collection Banner-->
    	<div class="collection-header">
			<div class="collection-hero">
        		<div class="collection-hero__image"><img class="blur-up lazyload" data-src="{% static 'belle/assets/images/cat-women1.jpg' %}" src="{% static 'belle/assets/images/cat-women1.jpg' %}" alt="Women" title="Women" /></div>
        		<div class="collection-hero__title-wrapper"><h1 class="collection-hero__title page-width">Shop Grid 7 Column</h1></div>
      		</div>
		</div>
        <!--End Collection Banner-->
        {% block content %}{% endblock content %}
        
    </div>
    <!--End Body Content-->
    
    <!--Footer-->
    <footer id="footer">
       
        <div class="site-footer">
        	<div class="container">
     			<!--Footer Links-->
            	<div class="footer-top">
                	
                
                <!--End Footer Links-->
                <hr>
                <div class="footer-bottom">
                	<div class="row">
                    	<!--Footer Copyright-->
	                	<div class="col-12 col-sm-12 col-md-6 col-lg-6 order-1 order-md-0 order-lg-0 order-sm-1 copyright text-sm-center text-md-left text-lg-left"><span></span> <a href="#">Myanmar K Power Company Limited</a></div>
                        <!--End Footer Copyright-->
                        <!--Footer Payment Icon-->
                        <div class="col-12 col-sm-12 col-md-6 col-lg-6 order-0 order-md-1 order-lg-1 order-sm-0 payment-icons text-right text-md-center">
                        	<ul class="payment-icons list--inline">
                        		<li><i class="icon fa fa-cc-visa" aria-hidden="true"></i></li>
                                <li><i class="icon fa fa-cc-mastercard" aria-hidden="true"></i></li>
                                <li><i class="icon fa fa-cc-discover" aria-hidden="true"></i></li>
                                <li><i class="icon fa fa-cc-paypal" aria-hidden="true"></i></li>
                                <li><i class="icon fa fa-cc-amex" aria-hidden="true"></i></li>
                                <li><i class="icon fa fa-credit-card" aria-hidden="true"></i></li>
                            </ul>
                        </div>
                        <!--End Footer Payment Icon-->
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!--End Footer-->
    
    <!--Scoll Top-->
    <span id="site-scroll"><i class="icon anm anm-angle-up-r"></i></span>
    <!--End Scoll Top-->

    
     <!-- Including Jquery -->
     <script src="{% static 'belle/assets/js/vendor/jquery-3.3.1.min.js' %}"></script>
     <script src="{% static 'belle/assets/js/vendor/jquery.cookie.js' %}"></script>
     <script src="{% static 'belle/assets/js/vendor/modernizr-3.6.0.min.js' %}"></script>
     <script src="{% static 'belle/assets/js/vendor/wow.min.js' %}"></script>
     <!-- Including Javascript -->
     <script src="{% static 'belle/assets/js/bootstrap.min.js' %}"></script>
     <script src="{% static 'belle/assets/js/plugins.js' %}"></script>
     <script src="{% static 'belle/assets/js/popper.min.js' %}"></script>
     <script src="{% static 'belle/assets/js/lazysizes.js' %}"></script>
     <script src="{% static 'belle/assets/js/main.js' %}"></script>
</div>
</div>
</body>

<!-- belle/shop-grid-7.html   11 Nov 2019 12:41:02 GMT -->
</html>

backend/templates/shop/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Myanmar K Power</title>
  <link rel="shortcut icon" type="image/png" href="{% static 'assets/images/logos/seodashlogo.png' %}" />
  <!-- <link rel="stylesheet" href="../../node_modules/simplebar/dist/simplebar.min.css"> -->
  <link rel="stylesheet" href="{% static 'assets/css/styles.min.css' %}" />
  
  <!-- data table  -->
  <link rel="stylesheet" href="{% static 'assets/libs/datatable/datatables.min.css' %}" />
  <link rel="stylesheet" href="{% static 'assets/libs/datatable/dataTables.bootstrap5.css' %}" />
</head>

<body>
  <!--  Body Wrapper -->
  <div class="page-wrapper" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
    data-sidebar-position="fixed" data-header-position="fixed">
    <!-- Sidebar Start -->
    <aside class="left-sidebar">
      <!-- Sidebar scroll-->
      <div>
        <div class="brand-logo d-flex align-items-center justify-content-between">
          <a href="#" class="text-nowrap logo-img mx-3">
            <img src="{% static 'assets/images/logos/head.png' %}" alt="" width="180" />
          </a>
          <div class="close-btn d-xl-none d-block sidebartoggler cursor-pointer" id="sidebarCollapse">
            <i class="ti ti-x fs-8"></i>
          </div>
        </div>
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav scroll-sidebar" data-simplebar="">
          <ul id="sidebarnav">
            <li class="nav-small-cap">
              <i class="ti ti-dots nav-small-cap-icon fs-6"></i>
              <span class="hide-menu">Home</span>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="{% url 'myapp:home' %}" aria-expanded="false">
                <span>
                  <iconify-icon icon="solar:home-smile-bold-duotone" class="fs-6"></iconify-icon>
                </span>
                <span class="hide-menu">Dashboard</span>
              </a>
            </li>
            <li class="nav-small-cap">
              <i class="ti ti-dots nav-small-cap-icon fs-6"></i>
              <span class="hide-menu">SETUP</span>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="{% url 'myapp:create_item' %}" aria-expanded="false">
                <span>
                  <iconify-icon icon="solar:layers-minimalistic-bold-duotone" class="fs-6"></iconify-icon>
                </span>
                <span class="hide-menu">Item Create</span>
              </a>
            </li>
            
            <li class="sidebar-item">
              <a class="sidebar-link" href="{% url 'myapp:category_list' %}" aria-expanded="false">
                <span>
                  <iconify-icon icon="solar:text-field-focus-bold-duotone" class="fs-6"></iconify-icon>
                </span>
                <span class="hide-menu">Category Menu</span>
              </a>
            </li>
            <li class="nav-small-cap">
              <iconify-icon icon="solar:menu-dots-linear" class="nav-small-cap-icon fs-6" class="fs-6"></iconify-icon>
              <span class="hide-menu">SHOP</span>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="./authentication-login.html" aria-expanded="false">
                <span>
                  <iconify-icon icon="solar:login-3-bold-duotone" class="fs-6"></iconify-icon>
                </span>
                <span class="hide-menu">Management</span>
              </a>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="{% url 'myapp:shopview1' %}" aria-expanded="false">
                <span>
                  <iconify-icon icon="solar:user-plus-rounded-bold-duotone" class="fs-6"></iconify-icon>
                </span>
                <span class="hide-menu">Shop1</span>
              </a>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="{% url 'myapp:shopview2' %}" aria-expanded="false">
                <span>
                  <iconify-icon icon="solar:user-plus-rounded-bold-duotone" class="fs-6"></iconify-icon>
                </span>
                <span class="hide-menu">Shop2</span>
              </a>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="{% url 'myapp:shopview1' %}" aria-expanded="false">
                <span>
                  <iconify-icon icon="solar:user-plus-rounded-bold-duotone" class="fs-6"></iconify-icon>
                </span>
                <span class="hide-menu">Shop3</span>
              </a>
            </li>
            
            
          </ul>
          <div class="unlimited-access hide-menu bg-primary-subtle position-relative mb-7 mt-7 rounded-3">
            <div class="d-flex">
              
              
            </div>
          </div>
        </nav>
        <!-- End Sidebar navigation -->
      </div>
      <!-- End Sidebar scroll-->
    </aside>
    <!--  Sidebar End -->
    <!--  Main wrapper -->
    <div class="body-wrapper">
      <!--  Header Start -->
      <header class="app-header">
        <nav class="navbar navbar-expand-lg navbar-light">
          <ul class="navbar-nav">
            <li class="nav-item d-block d-xl-none">
              <a class="nav-link sidebartoggler nav-icon-hover" id="headerCollapse" href="javascript:void(0)">
                <i class="ti ti-menu-2"></i>
              </a>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-item"><img src="{% static 'assets/images/profile/head.svg' %}" alt="" width="300" height="70" class=""></a>
           
            </li>
          </ul>
          <div class="navbar-collapse justify-content-end px-0" id="navbarNav">
            <ul class="navbar-nav flex-row ms-auto align-items-center justify-content-end">
              
              <li class="nav-item dropdown">
                <a class="nav-link nav-icon-hover" href="javascript:void(0)" id="drop2" data-bs-toggle="dropdown"
                  aria-expanded="false">
                  <img src="{% static 'assets/images/profile/user-2.jpg' %}" alt="" width="35" height="35" class="rounded-circle">
                </a>
                <div class="dropdown-menu dropdown-menu-end dropdown-menu-animate-up" aria-labelledby="drop2">
                  <div class="message-body">
                    <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                      <i class="ti ti-user fs-6"></i>
                      <p class="mb-0 fs-3">My Profile</p>
                    </a>
                    <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                      <i class="ti ti-mail fs-6"></i>
                      <p class="mb-0 fs-3">My Account</p>
                    </a>
                    <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                      <i class="ti ti-list-check fs-6"></i>
                      <p class="mb-0 fs-3">My Task</p>
                    </a>
                    <a href="./authentication-login.html" class="btn btn-outline-primary mx-3 mt-2 d-block">Logout</a>
                  </div>
                </div>
              </li>
            </ul>
          </div>
        </nav>
      </header>
      <!--  Header End -->
      <div class="container-fluid">
        {% block content %}
        {% endblock content %}
        <!-- <div class="card">
          <div class="card-body">
          </div>
        </div> -->
        
        

         <div class="py-6 px-6 text-center">
          <p class="mb-0 fs-4">Design and Developed by <a href="#" target="_blank"
              class="pe-1 text-primary text-decoration-underline">Realistic Infotech Group</a></p>
        </div>
      </div>
    </div>
  </div>
  <script src="{% static 'assets/libs/jquery/dist/jquery.min.js' %}"></script>
  <script src="{% static 'assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/libs/simplebar/dist/simplebar.js' %}"></script>
  <script src="{% static 'assets/js/sidebarmenu.js' %}"></script>
  <script src="{% static 'assets/js/app.min.js' %}"></script>
  <script src="https://cdn.jsdelivr.net/npm/iconify-icon@1.0.8/dist/iconify-icon.min.js"></script>

  <script src="{% static 'assets/libs/datatable/datatables.js' %}"></script>
  <script src="{% static 'assets/libs/datatable/dataTables.bootstrap5.js' %}"></script>
  <script src="{% static 'assets/libs/datatable/custom.js' %}"></script>

</body>

</html>

backend/templates/shop/create_item.html
{% extends 'shop/base.html' %}

{% block content %}



<div class="card">
    <div class="card-body">
      <h5 class="card-title fw-semibold mb-4">Item Lists</h5>
      <p><a href="#" data-bs-toggle="modal" data-bs-target="#createItem"><span class="badge rounded-pill text-bg-success">Add New</span></a></p>

 
  <!-- Modal -->
  <div class="modal fade" id="createItem" tabindex="-1" aria-labelledby="createItemLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="createItemLabel">Modal title</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          {{fm}}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>



    <table id="example" class="table table-striped" style="width:100%">
      <thead>
          <tr>
              <th>Photo</th>
              <th>Item Name</th>
              <th>Category</th>
              <th>PKG</th>
              <th>Price 1</th>
              <th>Price 2</th>
              <th>Price 3</th>
              <th>Action</th>
          </tr>
      </thead>
      <tbody>

          <tr>
              <td>Tiger Nixon</td>
              <td>System Architect</td>
              <td>Edinburgh</td>
              <td>61</td>
              <td>2011-04-25</td>
              <td>$320,800</td>
              <td>100000</td>
              <td>
                <a class="btn btn-sm btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><i class=" ti ti-settings h5 text-white"></i></a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'myapp:item_details' %}">detail</a></li>
                  <li><a class="dropdown-item" href="#">update</a></li>
                </ul>
              </td>
          </tr>
          
         
      </tbody>
      <tfoot>
        <tr>
            <th>Photo</th>
            <th>Item Name</th>
            <th>Category</th>
            <th>PKG</th>
            <th>Price 1</th>
            <th>Price 2</th>
            <th>Price 3</th>
            <th>Action</th>
        </tr>
      </tfoot>
  </table>
   </div>

    
  </div>

{% endblock content %}

backend/templates/shop/shopview1.html
<h1>Table View</h1>